export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const GET_CURRENT_QUESTION = 'GET_CURRENT_QUESTION';
export const ADD_QUESTION_TO_ANSWERED_QUESTIONS = 'ADD_QUESTION_TO_ANSWERED_QUESTIONS';
export const GET_ANSWERED_QUESTIONS = 'GET_ANSWERED_QUESTIONS';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const GET_QUESTIONS = 'GET_QUESTIONS';